name: CI

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches: ["main", "develop", "release*"]

  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Check coding styles
        run: yarn lint-solidity
      - name: run tests
        env:
          GOERLI_URL: ${{ secrets.GOERLI_URL }}
          MUMBAI_URL: ${{ secrets.MUMBAI_URL }}
        run: yarn test
