name: CI

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches: ["main", "CertiK_audit"]

  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      - name: Check coding styles
        uses: borales/actions-yarn@v4
        with:
          cmd: lint-solidity

      - name: Test the contracts
        uses: borales/actions-yarn@v4
        with:
          cmd: test # will run `yarn test` command
